In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
pd.read_csv("/Marketing_Finance_Project 2 (1).csv")

,OrderID,OrderDate,CustomerID,City,Age,Channel,Campaign,ProductCategory,Units,UnitPrice,DiscountPct,MarketingCost,COGS_per_unit,PaymentStatus,PaymentMethod
0,1001,01-01-2025,5039,NaN,21.0,Instagram Ads,Retargeting_Push,Digital Marketing Course,2,1999,0.20,1000.0,150.0,Pending,UPI
1,1002,02-01-2025,5029,Pune,31.0,Instagram Ads,Brand_Awareness,Digital Marketing Course,1,1999,0.00,200.0,150.0,Refunded,UPI
2,1003,03-01-2025,5015,Goa,31.0,Instagram Ads,New_Year_Blast,Workshop Pass,5,499,0.00,500.0,250.0,Paid,NaN
3,1004,04-01-2025,5043,Pune,29.0,Google Ads,Brand_Awareness,SAP Course,4,1999,0.20,200.0,400.0,Paid,UPI
4,1005,05-01-2025,5008,Pune,31.0,Instagram Ads,Brand_Awareness,SAP Course,2,1999,0.15,200.0,600.0,Paid,Card
5,1006,06-01-2025,5021,Goa,23.0,Referral,Retargeting_Push,E-book,1,1999,0.10,200.0,600.0,Refunded,NetBanking
6,1007,07-01-2025,5039,Bangalore,19.0,Organic,Retargeting_Push,SAP Course,4,999,NaN,NaN,150.0,Refunded,NaN
7,1008,08-01-2025,5019,Pune,31.0,Instagram Ads,Diwali_Sale,SAP Course,5,1499,0.00,200.0,150.0,Paid,NetBanking
8,1009,09-01-2025,5023,Pune,31.0,Google Ads,Diwali_Sale,SAP Course,4,799,0.15,1000.0,NaN,Paid,UPI
9,1010,10-01-2025,5011,Goa,21.0,Google Ads,New_Year_Blast,Data Analytics Course,1,999,0.10,500.0,600.0,Paid,UPI
10,1011,11-01-2025,5011,Pune,21.0,Instagram Ads,Diwali_Sale,E-book,4,1999,0.15,500.0,150.0,Paid,UPI
11,1012,12-01-2025,5024,Pune,25.0,Organic,Brand_Awareness,Digital Marketing Course,3,499,0.15,200.0,400.0,Paid,Card
12,1013,13-01-2025,5036,Goa,27.0,Instagram Ads,Retargeting_Push,Workshop Pass,4,1999,0.00,750.0,400.0,Paid,Card
13,1014,14-01-2025,5040,Goa,23.0,Google Ads,Diwali_Sale,Digital Marketing Course,2,1499,NaN,750.0,150.0,Refunded,NetBanking
14,1015,15-01-2025,5024,Belgaum,31.0,Facebook Ads,Diwali_Sale,E-book,2,1999,0.20,1000.0,150.0,Paid,UPI
15,1016,16-01-2025,5003,Bangalore,NaN,Referral,New_Year_Blast,Workshop Pass,3,499,0.00,200.0,600.0,Paid,NaN
16,1017,17-01-2025,5022,Bangalore,31.0,Google Ads,New_Year_Blast,E-book,1,1499,0.10,500.0,600.0,Pending,Card
17,1018,18-01-2025,5002,Pune,19.0,Instagram Ads,Brand_Awareness,SAP Course,2,1999,0.10,NaN,250.0,Refunded,NaN
18,1019,19-01-2025,5024,Bangalore,25.0,Referral,Retargeting_Push,Workshop Pass,5,1499,0.10,200.0,600.0,Refunded,Card
19,1020,20-01-2025,5044,Pune,27.0,Instagram Ads,New_Year_Blast,SAP Course,2,799,0.10,750.0,400.0,Paid,UPI
20,1021,21-01-2025,5030,Belgaum,33.0,Instagram Ads,Diwali_Sale,Digital Marketing Course,2,799,0.10,NaN,400.0,Paid,NetBanking
21,1022,22-01-2025,5038,Goa,25.0,Facebook Ads,Retargeting_Push,Digital Marketing Course,1,1999,0.15,500.0,150.0,Paid,UPI
22,1023,23-01-2025,5002,Goa,29.0,Referral,Retargeting_Push,Workshop Pass,4,1499,0.00,350.0,600.0,Paid,UPI
23,1024,24-01-2025,5021,Goa,27.0,Referral,Diwali_Sale,Workshop Pass,2,499,0.15,1000.0,250.0,Paid,Card
24,1025,25-01-2025,5033,NaN,31.0,Facebook Ads,New_Year_Blast,E-book,3,1999,0.20,1000.0,400.0,Paid,UPI
25,1026,26-01-2025,5012,Belgaum,31.0,Google Ads,Diwali_Sale,E-book,4,799,0.10,500.0,400.0,Paid,UPI
26,1027,27-01-2025,5022,Bangalore,27.0,Instagram Ads,Retargeting_Push,SAP Course,5,799,0.00,750.0,NaN,Paid,Card
27,1028,28-01-2025,5044,Bangalore,31.0,Organic,Referral_Bonus,Workshop Pass,1,1999,NaN,200.0,250.0,Paid,NetBanking
28,1029,29-01-2025,5025,Belgaum,23.0,Instagram Ads,Referral_Bonus,Digital Marketing Course,5,1499,0.00,750.0,400.0,Paid,NetBanking
29,1030,30-01-2025,5049,Belgaum,27.0,Instagram Ads,Brand_Awareness,E-book,4,799,0.15,500.0,400.0,Paid,Card
30,1031,31-01-2025,5027,Belgaum,25.0,Google Ads,Diwali_Sale,E-book,4,1499,0.00,1000.0,250.0,Paid,Card
31,1032,01-02-2025,5042,Belgaum,27.0,Instagram Ads,Diwali_Sale,Digital Marketing Course,4,799,NaN,NaN,400.0,Paid,Card
32,1033,02-02-2025,5028,Goa,33.0,Facebook Ads,Brand_Awareness,E-book,5,799,0.20,1000.0,150.0,Paid,Card
33,1034,03-02-2025,5016,Hubli,31.0,Facebook Ads,Brand_Awareness,SAP Course,4,999,0.00,200.0,150.0,Paid,Card
34,1035,04-02-2025,5015,NaN,23.0,Referral,Brand_Awareness,Workshop Pass,5,799,0.00,1000.0,250.0,Paid,NetBanking
35,1036,05-02-2025,5047,Belgaum,23.0,Organic,Retargeting_Push,Digital Marketing Course,4,499,0.00,1000.0,600.0,Paid,NetBanking
36,1037,06-02-2025,5044,Hubli,NaN,Instagram Ads,Diwali_Sale,Workshop Pass,3,1999,0.00,350.0,250.0,Paid,Card
37,1038,07-02-2025,5003,Hubli,NaN,Instagram Ads,Retargeting_Push,E-book,4,1999,0.20,350.0,250.0,Paid,UPI
38,1039,08-02-2025,5037,Belgaum,21.0,Google Ads,Brand_Awareness,E-book,5,1499,0.10,350.0,600.0,Refunded,Card
39,1040,09-02-2025,5007,NaN,21.0,Facebook Ads,Diwali_Sale,Digital Marketing Course,2,799,0.00,1000.0,600.0,Paid,UPI
40,1041,10-02-2025,5021,Bangalore,27.0,Organic,Retargeting_Push,SAP Course,4,499,0.00,500.0,600.0,Paid,Card
41,1042,11-02-2025,5009,Pune,NaN,Referral,Retargeting_Push,Data Analytics Course,2,1499,0.20,1000.0,150.0,Refunded,Card
42,1043,12-02-2025,5039,Pune,19.0,Facebook Ads,Brand_Awareness,Digital Marketing Course,3,999,0.20,500.0,400.0,Paid,NetBanking
43,1044,13-02-2025,5018,Belgaum,27.0,Referral,Diwali_Sale,Data Analytics Course,1,1499,0.15,500.0,150.0,Pending,NaN
44,1045,14-02-2025,5004,Goa,29.0,Google Ads,Brand_Awareness,Data Analytics Course,3,1499,0.00,350.0,NaN,Paid,UPI
45,1046,15-02-2025,5025,Belgaum,25.0,Google Ads,Diwali_Sale,SAP Course,4,799,0.15,750.0,150.0,Paid,NetBanking
46,1047,16-02-2025,5014,Goa,25.0,Instagram Ads,Referral_Bonus,Data Analytics Course,2,999,0.20,200.0,400.0,Paid,NetBanking
47,1048,17-02-2025,5009,Pune,25.0,Organic,New_Year_Blast,Data Analytics Course,2,1499,0.20,350.0,150.0,Pending,NetBanking
48,1049,18-02-2025,5026,Belgaum,25.0,Referral,New_Year_Blast,SAP Course,5,499,0.10,350.0,600.0,Paid,NetBanking
49,1050,19-02-2025,5002,Bangalore,25.0,Facebook Ads,New_Year_Blast,Data Analytics Course,2,499,0.00,750.0,250.0,Refunded,UPI
50,1051,20-02-2025,5020,Hubli,29.0,Google Ads,Brand_Awareness,Data Analytics Course,5,1999,0.15,200.0,150.0,Paid,UPI
51,1052,21-02-2025,5028,Goa,29.0,Instagram Ads,Referral_Bonus,Data Analytics Course,1,999,NaN,NaN,400.0,Pending,Card
52,1053,22-02-2025,5047,NaN,23.0,Instagram Ads,Diwali_Sale,Digital Marketing Course,4,999,0.20,1000.0,600.0,Paid,Card
53,1054,23-02-2025,5007,Hubli,33.0,Referral,Retargeting_Push,Digital Marketing Course,5,1999,0.15,350.0,150.0,Pending,NetBanking
54,1055,24-02-2025,5044,Belgaum,NaN,Google Ads,Diwali_Sale,Digital Marketing Course,1,1499,0.10,200.0,150.0,Paid,NetBanking
55,1056,25-02-2025,5008,Hubli,31.0,Organic,Retargeting_Push,SAP Course,2,999,0.20,350.0,NaN,Paid,NetBanking
56,1057,26-02-2025,5047,Bangalore,25.0,Google Ads,Diwali_Sale,E-book,2,499,0.00,500.0,150.0,Paid,Card
57,1058,27-02-2025,5035,Hubli,19.0,Referral,Referral_Bonus,Data Analytics Course,1,499,0.20,350.0,250.0,Paid,Card
58,1059,28-02-2025,5014,Belgaum,31.0,Referral,Retargeting_Push,Data Analytics Course,2,799,0.00,350.0,150.0,Paid,Card
59,1060,01-03-2025,5017,Bangalore,29.0,Google Ads,Brand_Awareness,SAP Course,1,999,0.15,1000.0,NaN,Paid,Card

In [ ]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          60 non-null     int64
 1   OrderDate        60 non-null     object
 2   CustomerID       60 non-null     int64
 3   City             55 non-null     object
 4   Age              55 non-null     float64
 5   Channel          60 non-null     object
 6   Campaign         60 non-null     object
 7   ProductCategory  60 non-null     object
 8   Units            60 non-null     int64
 9   UnitPrice        60 non-null     int64
 10  DiscountPct      55 non-null     float64
 11  MarketingCost    55 non-null     float64
 12  COGS_per_unit    55 non-null     float64
 13  PaymentStatus    60 non-null     object
 14  PaymentMethod    55 non-null     object
dtypes: float64(4), int64(4), object(7)
memory usage: 7.2+ KB

In [ ]:
df.isnull().sum()

OrderID            0
OrderDate          0
CustomerID         0
City               5
Age                5
Channel            0
Campaign           0
ProductCategory    0
Units              0
UnitPrice          0
DiscountPct        5
MarketingCost      5
COGS_per_unit      5
PaymentStatus      0
PaymentMethod      5
dtype: int64

In [ ]:
 df['City'].fillna("Unknown")

0       Unknown
1          Pune
2           Goa
3          Pune
4          Pune
5           Goa
6     Bangalore
7          Pune
8          Pune
9           Goa
10         Pune
11         Pune
12          Goa
13          Goa
14      Belgaum
15    Bangalore
16    Bangalore
17         Pune
18    Bangalore
19         Pune
20      Belgaum
21          Goa
22          Goa
23          Goa
24      Unknown
25      Belgaum
26    Bangalore
27    Bangalore
28      Belgaum
29      Belgaum
30      Belgaum
31      Belgaum
32          Goa
33        Hubli
34      Unknown
35      Belgaum
36        Hubli
37        Hubli
38      Belgaum
39      Unknown
40    Bangalore
41         Pune
42         Pune
43      Belgaum
44          Goa
45      Belgaum
46          Goa
47         Pune
48      Belgaum
49    Bangalore
50        Hubli
51          Goa
52      Unknown
53        Hubli
54      Belgaum
55        Hubli
56    Bangalore
57        Hubli
58      Belgaum
59    Bangalore
Name: City, dtype: object

In [ ]:
 df['PaymentMethod'].fillna("Unknown")

0            UPI
1            UPI
2        Unknown
3            UPI
4           Card
5     NetBanking
6        Unknown
7     NetBanking
8            UPI
9            UPI
10           UPI
11          Card
12          Card
13    NetBanking
14           UPI
15       Unknown
16          Card
17       Unknown
18          Card
19           UPI
20    NetBanking
21           UPI
22           UPI
23          Card
24           UPI
25           UPI
26          Card
27    NetBanking
28    NetBanking
29          Card
30          Card
31          Card
32          Card
33          Card
34    NetBanking
35    NetBanking
36          Card
37           UPI
38          Card
39           UPI
40          Card
41          Card
42    NetBanking
43       Unknown
44           UPI
45    NetBanking
46    NetBanking
47    NetBanking
48    NetBanking
49           UPI
50           UPI
51          Card
52          Card
53    NetBanking
54    NetBanking
55    NetBanking
56          Card
57          Card
58          Card
59          Card
Name: PaymentMethod, dtype: object

In [ ]:
 df['Age'].fillna(df["Age"].median())

0     21.0
1     31.0
2     31.0
3     29.0
4     31.0
5     23.0
6     19.0
7     31.0
8     31.0
9     21.0
10    21.0
11    25.0
12    27.0
13    23.0
14    31.0
15    27.0
16    31.0
17    19.0
18    25.0
19    27.0
20    33.0
21    25.0
22    29.0
23    27.0
24    31.0
25    31.0
26    27.0
27    31.0
28    23.0
29    27.0
30    25.0
31    27.0
32    33.0
33    31.0
34    23.0
35    23.0
36    27.0
37    27.0
38    21.0
39    21.0
40    27.0
41    27.0
42    19.0
43    27.0
44    29.0
45    25.0
46    25.0
47    25.0
48    25.0
49    25.0
50    29.0
51    29.0
52    23.0
53    33.0
54    27.0
55    31.0
56    25.0
57    19.0
58    31.0
59    29.0
Name: Age, dtype: float64

In [ ]:
 df['DiscountPct'].fillna(0)

0     0.20
1     0.00
2     0.00
3     0.20
4     0.15
5     0.10
6     0.00
7     0.00
8     0.15
9     0.10
10    0.15
11    0.15
12    0.00
13    0.00
14    0.20
15    0.00
16    0.10
17    0.10
18    0.10
19    0.10
20    0.10
21    0.15
22    0.00
23    0.15
24    0.20
25    0.10
26    0.00
27    0.00
28    0.00
29    0.15
30    0.00
31    0.00
32    0.20
33    0.00
34    0.00
35    0.00
36    0.00
37    0.20
38    0.10
39    0.00
40    0.00
41    0.20
42    0.20
43    0.15
44    0.00
45    0.15
46    0.20
47    0.20
48    0.10
49    0.00
50    0.15
51    0.00
52    0.20
53    0.15
54    0.10
55    0.20
56    0.00
57    0.20
58    0.00
59    0.15
Name: DiscountPct, dtype: float64

In [ ]:
  df['MarketingCost'].fillna(df["MarketingCost"].median())

0     1000.0
1      200.0
2      500.0
3      200.0
4      200.0
5      200.0
6      500.0
7      200.0
8     1000.0
9      500.0
10     500.0
11     200.0
12     750.0
13     750.0
14    1000.0
15     200.0
16     500.0
17     500.0
18     200.0
19     750.0
20     500.0
21     500.0
22     350.0
23    1000.0
24    1000.0
25     500.0
26     750.0
27     200.0
28     750.0
29     500.0
30    1000.0
31     500.0
32    1000.0
33     200.0
34    1000.0
35    1000.0
36     350.0
37     350.0
38     350.0
39    1000.0
40     500.0
41    1000.0
42     500.0
43     500.0
44     350.0
45     750.0
46     200.0
47     350.0
48     350.0
49     750.0
50     200.0
51     500.0
52    1000.0
53     350.0
54     200.0
55     350.0
56     500.0
57     350.0
58     350.0
59    1000.0
Name: MarketingCost, dtype: float64

In [ ]:
 df['COGS_per_unit'].fillna(df["COGS_per_unit"].median())

0     150.0
1     150.0
2     250.0
3     400.0
4     600.0
5     600.0
6     150.0
7     150.0
8     250.0
9     600.0
10    150.0
11    400.0
12    400.0
13    150.0
14    150.0
15    600.0
16    600.0
17    250.0
18    600.0
19    400.0
20    400.0
21    150.0
22    600.0
23    250.0
24    400.0
25    400.0
26    250.0
27    250.0
28    400.0
29    400.0
30    250.0
31    400.0
32    150.0
33    150.0
34    250.0
35    600.0
36    250.0
37    250.0
38    600.0
39    600.0
40    600.0
41    150.0
42    400.0
43    150.0
44    250.0
45    150.0
46    400.0
47    150.0
48    600.0
49    250.0
50    150.0
51    400.0
52    600.0
53    150.0
54    150.0
55    250.0
56    150.0
57    250.0
58    150.0
59    250.0
Name: COGS_per_unit, dtype: float64

In [ ]:
df.isnull().sum()

OrderID            0
OrderDate          0
CustomerID         0
City               5
Age                5
Channel            0
Campaign           0
ProductCategory    0
Units              0
UnitPrice          0
DiscountPct        5
MarketingCost      5
COGS_per_unit      5
PaymentStatus      0
PaymentMethod      5
dtype: int64

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
50    False
51    False
52    False
53    False
54    False
55    False
56    False
57    False
58    False
59    False
dtype: bool

In [ ]:
print(df)

    OrderID   OrderDate  CustomerID       City   Age        Channel  \
0      1001  01-01-2025        5039        NaN  21.0  Instagram Ads
1      1002  02-01-2025        5029       Pune  31.0  Instagram Ads
2      1003  03-01-2025        5015        Goa  31.0  Instagram Ads
3      1004  04-01-2025        5043       Pune  29.0     Google Ads
4      1005  05-01-2025        5008       Pune  31.0  Instagram Ads
5      1006  06-01-2025        5021        Goa  23.0       Referral
6      1007  07-01-2025        5039  Bangalore  19.0        Organic
7      1008  08-01-2025        5019       Pune  31.0  Instagram Ads
8      1009  09-01-2025        5023       Pune  31.0     Google Ads
9      1010  10-01-2025        5011        Goa  21.0     Google Ads
10     1011  11-01-2025        5011       Pune  21.0  Instagram Ads
11     1012  12-01-2025        5024       Pune  25.0        Organic
12     1013  13-01-2025        5036        Goa  27.0  Instagram Ads
13     1014  14-01-2025        5040        Goa  23.0     Google Ads
14     1015  15-01-2025        5024    Belgaum  31.0   Facebook Ads
15     1016  16-01-2025        5003  Bangalore   NaN       Referral
16     1017  17-01-2025        5022  Bangalore  31.0     Google Ads
17     1018  18-01-2025        5002       Pune  19.0  Instagram Ads
18     1019  19-01-2025        5024  Bangalore  25.0       Referral
19     1020  20-01-2025        5044       Pune  27.0  Instagram Ads
20     1021  21-01-2025        5030    Belgaum  33.0  Instagram Ads
21     1022  22-01-2025        5038        Goa  25.0   Facebook Ads
22     1023  23-01-2025        5002        Goa  29.0       Referral
23     1024  24-01-2025        5021        Goa  27.0       Referral
24     1025  25-01-2025        5033        NaN  31.0   Facebook Ads
25     1026  26-01-2025        5012    Belgaum  31.0     Google Ads
26     1027  27-01-2025        5022  Bangalore  27.0  Instagram Ads
27     1028  28-01-2025        5044  Bangalore  31.0        Organic
28     1029  29-01-2025        5025    Belgaum  23.0  Instagram Ads
29     1030  30-01-2025        5049    Belgaum  27.0  Instagram Ads
30     1031  31-01-2025        5027    Belgaum  25.0     Google Ads
31     1032  01-02-2025        5042    Belgaum  27.0  Instagram Ads
32     1033  02-02-2025        5028        Goa  33.0   Facebook Ads
33     1034  03-02-2025        5016      Hubli  31.0   Facebook Ads
34     1035  04-02-2025        5015        NaN  23.0       Referral
35     1036  05-02-2025        5047    Belgaum  23.0        Organic
36     1037  06-02-2025        5044      Hubli   NaN  Instagram Ads
37     1038  07-02-2025        5003      Hubli   NaN  Instagram Ads
38     1039  08-02-2025        5037    Belgaum  21.0     Google Ads
39     1040  09-02-2025        5007        NaN  21.0   Facebook Ads
40     1041  10-02-2025        5021  Bangalore  27.0        Organic
41     1042  11-02-2025        5009       Pune   NaN       Referral
42     1043  12-02-2025        5039       Pune  19.0   Facebook Ads
43     1044  13-02-2025        5018    Belgaum  27.0       Referral
44     1045  14-02-2025        5004        Goa  29.0     Google Ads
45     1046  15-02-2025        5025    Belgaum  25.0     Google Ads
46     1047  16-02-2025        5014        Goa  25.0  Instagram Ads
47     1048  17-02-2025        5009       Pune  25.0        Organic
48     1049  18-02-2025        5026    Belgaum  25.0       Referral
49     1050  19-02-2025        5002  Bangalore  25.0   Facebook Ads
50     1051  20-02-2025        5020      Hubli  29.0     Google Ads
51     1052  21-02-2025        5028        Goa  29.0  Instagram Ads
52     1053  22-02-2025        5047        NaN  23.0  Instagram Ads
53     1054  23-02-2025        5007      Hubli  33.0       Referral
54     1055  24-02-2025        5044    Belgaum   NaN     Google Ads
55     1056  25-02-2025        5008      Hubli  31.0        Organic
56     1057  26-02-2025        5047  Bangalore  25.0     Google Ads
57     1058  27-02-2025        5035      Hubli  19.0       Referral
58     1059  28-02-2025        5014    Belgaum  31.0       Referral
59     1060  01-03-2025        5017  Bangalore  29.0     Google Ads

            Campaign           ProductCategory  Units  UnitPrice  DiscountPct  \
0   Retargeting_Push  Digital Marketing Course      2       1999         0.20
1    Brand_Awareness  Digital Marketing Course      1       1999         0.00
2     New_Year_Blast             Workshop Pass      5        499         0.00
3    Brand_Awareness                SAP Course      4       1999         0.20
4    Brand_Awareness                SAP Course      2       1999         0.15
5   Retargeting_Push                    E-book      1       1999         0.10
6   Retargeting_Push                SAP Course      4        999          NaN
7        Diwali_Sale                SAP Course      5       1499         0.00
8        Diwali_Sale                SAP Course      4        799         0.15
9     New_Year_Blast     Data Analytics Course      1        999         0.10
10       Diwali_Sale                    E-book      4       1999         0.15
11   Brand_Awareness  Digital Marketing Course      3        499         0.15
12  Retargeting_Push             Workshop Pass      4       1999         0.00
13       Diwali_Sale  Digital Marketing Course      2       1499          NaN
14       Diwali_Sale                    E-book      2       1999         0.20
15    New_Year_Blast             Workshop Pass      3        499         0.00
16    New_Year_Blast                    E-book      1       1499         0.10
17   Brand_Awareness                SAP Course      2       1999         0.10
18  Retargeting_Push             Workshop Pass      5       1499         0.10
19    New_Year_Blast                SAP Course      2        799         0.10
20       Diwali_Sale  Digital Marketing Course      2        799         0.10
21  Retargeting_Push  Digital Marketing Course      1       1999         0.15
22  Retargeting_Push             Workshop Pass      4       1499         0.00
23       Diwali_Sale             Workshop Pass      2        499         0.15
24    New_Year_Blast                    E-book      3       1999         0.20
25       Diwali_Sale                    E-book      4        799         0.10
26  Retargeting_Push                SAP Course      5        799         0.00
27    Referral_Bonus             Workshop Pass      1       1999          NaN
28    Referral_Bonus  Digital Marketing Course      5       1499         0.00
29   Brand_Awareness                    E-book      4        799         0.15
30       Diwali_Sale                    E-book      4       1499         0.00
31       Diwali_Sale  Digital Marketing Course      4        799          NaN
32   Brand_Awareness                    E-book      5        799         0.20
33   Brand_Awareness                SAP Course      4        999         0.00
34   Brand_Awareness             Workshop Pass      5        799         0.00
35  Retargeting_Push  Digital Marketing Course      4        499         0.00
36       Diwali_Sale             Workshop Pass      3       1999         0.00
37  Retargeting_Push                    E-book      4       1999         0.20
38   Brand_Awareness                    E-book      5       1499         0.10
39       Diwali_Sale  Digital Marketing Course      2        799         0.00
40  Retargeting_Push                SAP Course      4        499         0.00
41  Retargeting_Push     Data Analytics Course      2       1499         0.20
42   Brand_Awareness  Digital Marketing Course      3        999         0.20
43       Diwali_Sale     Data Analytics Course      1       1499         0.15
44   Brand_Awareness     Data Analytics Course      3       1499         0.00
45       Diwali_Sale                SAP Course      4        799         0.15
46    Referral_Bonus     Data Analytics Course      2        999         0.20
47    New_Year_Blast     Data Analytics Course      2       1499         0.20
48    New_Year_Blast                SAP Course      5        499         0.10
49    New_Year_Blast     Data Analytics Course      2        499         0.00
50   Brand_Awareness     Data Analytics Course      5       1999         0.15
51    Referral_Bonus     Data Analytics Course      1        999          NaN
52       Diwali_Sale  Digital Marketing Course      4        999         0.20
53  Retargeting_Push  Digital Marketing Course      5       1999         0.15
54       Diwali_Sale  Digital Marketing Course      1       1499         0.10
55  Retargeting_Push                SAP Course      2        999         0.20
56       Diwali_Sale                    E-book      2        499         0.00
57    Referral_Bonus     Data Analytics Course      1        499         0.20
58  Retargeting_Push     Data Analytics Course      2        799         0.00
59   Brand_Awareness                SAP Course      1        999         0.15

    MarketingCost  COGS_per_unit PaymentStatus PaymentMethod
0          1000.0          150.0       Pending           UPI
1           200.0          150.0      Refunded           UPI
2           500.0          250.0          Paid           NaN
3           200.0          400.0          Paid           UPI
4           200.0          600.0          Paid          Card
5           200.0          600.0      Refunded    NetBanking
6             NaN          150.0      Refunded           NaN
7           200.0          150.0          Paid    NetBanking
8          1000.0            NaN          Paid           UPI
9           500.0          600.0          Paid           UPI
10          500.0          150.0          Paid           UPI
11          200.0          400.0          Paid          Card
12          750.0          400.0          Paid          Card
13          750.0          150.0      Refunded    NetBanking
14         1000.0          150.0          Paid           UPI
15          200.0          600.0          Paid           NaN
16          500.0          600.0       Pending          Card
17            NaN          250.0      Refunded           NaN
18          200.0          600.0      Refunded          Card
19          750.0          400.0          Paid           UPI
20            NaN          400.0          Paid    NetBanking
21          500.0          150.0          Paid           UPI
22          350.0          600.0          Paid           UPI
23         1000.0          250.0          Paid          Card
24         1000.0          400.0          Paid           UPI
25          500.0          400.0          Paid           UPI
26          750.0            NaN          Paid          Card
27          200.0          250.0          Paid    NetBanking
28          750.0          400.0          Paid    NetBanking
29          500.0          400.0          Paid          Card
30         1000.0          250.0          Paid          Card
31            NaN          400.0          Paid          Card
32         1000.0          150.0          Paid          Card
33          200.0          150.0          Paid          Card
34         1000.0          250.0          Paid    NetBanking
35         1000.0          600.0          Paid    NetBanking
36          350.0          250.0          Paid          Card
37          350.0          250.0          Paid           UPI
38          350.0          600.0      Refunded          Card
39         1000.0          600.0          Paid           UPI
40          500.0          600.0          Paid          Card
41         1000.0          150.0      Refunded          Card
42          500.0          400.0          Paid    NetBanking
43          500.0          150.0       Pending           NaN
44          350.0            NaN          Paid           UPI
45          750.0          150.0          Paid    NetBanking
46          200.0          400.0          Paid    NetBanking
47          350.0          150.0       Pending    NetBanking
48          350.0          600.0          Paid    NetBanking
49          750.0          250.0      Refunded           UPI
50          200.0          150.0          Paid           UPI
51            NaN          400.0       Pending          Card
52         1000.0          600.0          Paid          Card
53          350.0          150.0       Pending    NetBanking
54          200.0          150.0          Paid    NetBanking
55          350.0            NaN          Paid    NetBanking
56          500.0          150.0          Paid          Card
57          350.0          250.0          Paid          Card
58          350.0          150.0          Paid          Card
59         1000.0            NaN          Paid          Card

In [ ]:
print(df)

    OrderID   OrderDate  CustomerID       City   Age        Channel  \
0      1001  01-01-2025        5039        NaN  21.0  Instagram Ads
1      1002  02-01-2025        5029       Pune  31.0  Instagram Ads
2      1003  03-01-2025        5015        Goa  31.0  Instagram Ads
3      1004  04-01-2025        5043       Pune  29.0     Google Ads
4      1005  05-01-2025        5008       Pune  31.0  Instagram Ads
5      1006  06-01-2025        5021        Goa  23.0       Referral
6      1007  07-01-2025        5039  Bangalore  19.0        Organic
7      1008  08-01-2025        5019       Pune  31.0  Instagram Ads
8      1009  09-01-2025        5023       Pune  31.0     Google Ads
9      1010  10-01-2025        5011        Goa  21.0     Google Ads
10     1011  11-01-2025        5011       Pune  21.0  Instagram Ads
11     1012  12-01-2025        5024       Pune  25.0        Organic
12     1013  13-01-2025        5036        Goa  27.0  Instagram Ads
13     1014  14-01-2025        5040        Goa  23.0     Google Ads
14     1015  15-01-2025        5024    Belgaum  31.0   Facebook Ads
15     1016  16-01-2025        5003  Bangalore   NaN       Referral
16     1017  17-01-2025        5022  Bangalore  31.0     Google Ads
17     1018  18-01-2025        5002       Pune  19.0  Instagram Ads
18     1019  19-01-2025        5024  Bangalore  25.0       Referral
19     1020  20-01-2025        5044       Pune  27.0  Instagram Ads
20     1021  21-01-2025        5030    Belgaum  33.0  Instagram Ads
21     1022  22-01-2025        5038        Goa  25.0   Facebook Ads
22     1023  23-01-2025        5002        Goa  29.0       Referral
23     1024  24-01-2025        5021        Goa  27.0       Referral
24     1025  25-01-2025        5033        NaN  31.0   Facebook Ads
25     1026  26-01-2025        5012    Belgaum  31.0     Google Ads
26     1027  27-01-2025        5022  Bangalore  27.0  Instagram Ads
27     1028  28-01-2025        5044  Bangalore  31.0        Organic
28     1029  29-01-2025        5025    Belgaum  23.0  Instagram Ads
29     1030  30-01-2025        5049    Belgaum  27.0  Instagram Ads
30     1031  31-01-2025        5027    Belgaum  25.0     Google Ads
31     1032  01-02-2025        5042    Belgaum  27.0  Instagram Ads
32     1033  02-02-2025        5028        Goa  33.0   Facebook Ads
33     1034  03-02-2025        5016      Hubli  31.0   Facebook Ads
34     1035  04-02-2025        5015        NaN  23.0       Referral
35     1036  05-02-2025        5047    Belgaum  23.0        Organic
36     1037  06-02-2025        5044      Hubli   NaN  Instagram Ads
37     1038  07-02-2025        5003      Hubli   NaN  Instagram Ads
38     1039  08-02-2025        5037    Belgaum  21.0     Google Ads
39     1040  09-02-2025        5007        NaN  21.0   Facebook Ads
40     1041  10-02-2025        5021  Bangalore  27.0        Organic
41     1042  11-02-2025        5009       Pune   NaN       Referral
42     1043  12-02-2025        5039       Pune  19.0   Facebook Ads
43     1044  13-02-2025        5018    Belgaum  27.0       Referral
44     1045  14-02-2025        5004        Goa  29.0     Google Ads
45     1046  15-02-2025        5025    Belgaum  25.0     Google Ads
46     1047  16-02-2025        5014        Goa  25.0  Instagram Ads
47     1048  17-02-2025        5009       Pune  25.0        Organic
48     1049  18-02-2025        5026    Belgaum  25.0       Referral
49     1050  19-02-2025        5002  Bangalore  25.0   Facebook Ads
50     1051  20-02-2025        5020      Hubli  29.0     Google Ads
51     1052  21-02-2025        5028        Goa  29.0  Instagram Ads
52     1053  22-02-2025        5047        NaN  23.0  Instagram Ads
53     1054  23-02-2025        5007      Hubli  33.0       Referral
54     1055  24-02-2025        5044    Belgaum   NaN     Google Ads
55     1056  25-02-2025        5008      Hubli  31.0        Organic
56     1057  26-02-2025        5047  Bangalore  25.0     Google Ads
57     1058  27-02-2025        5035      Hubli  19.0       Referral
58     1059  28-02-2025        5014    Belgaum  31.0       Referral
59     1060  01-03-2025        5017  Bangalore  29.0     Google Ads

            Campaign           ProductCategory  Units  UnitPrice  DiscountPct  \
0   Retargeting_Push  Digital Marketing Course      2       1999         0.20
1    Brand_Awareness  Digital Marketing Course      1       1999         0.00
2     New_Year_Blast             Workshop Pass      5        499         0.00
3    Brand_Awareness                SAP Course      4       1999         0.20
4    Brand_Awareness                SAP Course      2       1999         0.15
5   Retargeting_Push                    E-book      1       1999         0.10
6   Retargeting_Push                SAP Course      4        999          NaN
7        Diwali_Sale                SAP Course      5       1499         0.00
8        Diwali_Sale                SAP Course      4        799         0.15
9     New_Year_Blast     Data Analytics Course      1        999         0.10
10       Diwali_Sale                    E-book      4       1999         0.15
11   Brand_Awareness  Digital Marketing Course      3        499         0.15
12  Retargeting_Push             Workshop Pass      4       1999         0.00
13       Diwali_Sale  Digital Marketing Course      2       1499          NaN
14       Diwali_Sale                    E-book      2       1999         0.20
15    New_Year_Blast             Workshop Pass      3        499         0.00
16    New_Year_Blast                    E-book      1       1499         0.10
17   Brand_Awareness                SAP Course      2       1999         0.10
18  Retargeting_Push             Workshop Pass      5       1499         0.10
19    New_Year_Blast                SAP Course      2        799         0.10
20       Diwali_Sale  Digital Marketing Course      2        799         0.10
21  Retargeting_Push  Digital Marketing Course      1       1999         0.15
22  Retargeting_Push             Workshop Pass      4       1499         0.00
23       Diwali_Sale             Workshop Pass      2        499         0.15
24    New_Year_Blast                    E-book      3       1999         0.20
25       Diwali_Sale                    E-book      4        799         0.10
26  Retargeting_Push                SAP Course      5        799         0.00
27    Referral_Bonus             Workshop Pass      1       1999          NaN
28    Referral_Bonus  Digital Marketing Course      5       1499         0.00
29   Brand_Awareness                    E-book      4        799         0.15
30       Diwali_Sale                    E-book      4       1499         0.00
31       Diwali_Sale  Digital Marketing Course      4        799          NaN
32   Brand_Awareness                    E-book      5        799         0.20
33   Brand_Awareness                SAP Course      4        999         0.00
34   Brand_Awareness             Workshop Pass      5        799         0.00
35  Retargeting_Push  Digital Marketing Course      4        499         0.00
36       Diwali_Sale             Workshop Pass      3       1999         0.00
37  Retargeting_Push                    E-book      4       1999         0.20
38   Brand_Awareness                    E-book      5       1499         0.10
39       Diwali_Sale  Digital Marketing Course      2        799         0.00
40  Retargeting_Push                SAP Course      4        499         0.00
41  Retargeting_Push     Data Analytics Course      2       1499         0.20
42   Brand_Awareness  Digital Marketing Course      3        999         0.20
43       Diwali_Sale     Data Analytics Course      1       1499         0.15
44   Brand_Awareness     Data Analytics Course      3       1499         0.00
45       Diwali_Sale                SAP Course      4        799         0.15
46    Referral_Bonus     Data Analytics Course      2        999         0.20
47    New_Year_Blast     Data Analytics Course      2       1499         0.20
48    New_Year_Blast                SAP Course      5        499         0.10
49    New_Year_Blast     Data Analytics Course      2        499         0.00
50   Brand_Awareness     Data Analytics Course      5       1999         0.15
51    Referral_Bonus     Data Analytics Course      1        999          NaN
52       Diwali_Sale  Digital Marketing Course      4        999         0.20
53  Retargeting_Push  Digital Marketing Course      5       1999         0.15
54       Diwali_Sale  Digital Marketing Course      1       1499         0.10
55  Retargeting_Push                SAP Course      2        999         0.20
56       Diwali_Sale                    E-book      2        499         0.00
57    Referral_Bonus     Data Analytics Course      1        499         0.20
58  Retargeting_Push     Data Analytics Course      2        799         0.00
59   Brand_Awareness                SAP Course      1        999         0.15

    MarketingCost  COGS_per_unit PaymentStatus PaymentMethod
0          1000.0          150.0       Pending           UPI
1           200.0          150.0      Refunded           UPI
2           500.0          250.0          Paid           NaN
3           200.0          400.0          Paid           UPI
4           200.0          600.0          Paid          Card
5           200.0          600.0      Refunded    NetBanking
6             NaN          150.0      Refunded           NaN
7           200.0          150.0          Paid    NetBanking
8          1000.0            NaN          Paid           UPI
9           500.0          600.0          Paid           UPI
10          500.0          150.0          Paid           UPI
11          200.0          400.0          Paid          Card
12          750.0          400.0          Paid          Card
13          750.0          150.0      Refunded    NetBanking
14         1000.0          150.0          Paid           UPI
15          200.0          600.0          Paid           NaN
16          500.0          600.0       Pending          Card
17            NaN          250.0      Refunded           NaN
18          200.0          600.0      Refunded          Card
19          750.0          400.0          Paid           UPI
20            NaN          400.0          Paid    NetBanking
21          500.0          150.0          Paid           UPI
22          350.0          600.0          Paid           UPI
23         1000.0          250.0          Paid          Card
24         1000.0          400.0          Paid           UPI
25          500.0          400.0          Paid           UPI
26          750.0            NaN          Paid          Card
27          200.0          250.0          Paid    NetBanking
28          750.0          400.0          Paid    NetBanking
29          500.0          400.0          Paid          Card
30         1000.0          250.0          Paid          Card
31            NaN          400.0          Paid          Card
32         1000.0          150.0          Paid          Card
33          200.0          150.0          Paid          Card
34         1000.0          250.0          Paid    NetBanking
35         1000.0          600.0          Paid    NetBanking
36          350.0          250.0          Paid          Card
37          350.0          250.0          Paid           UPI
38          350.0          600.0      Refunded          Card
39         1000.0          600.0          Paid           UPI
40          500.0          600.0          Paid          Card
41         1000.0          150.0      Refunded          Card
42          500.0          400.0          Paid    NetBanking
43          500.0          150.0       Pending           NaN
44          350.0            NaN          Paid           UPI
45          750.0          150.0          Paid    NetBanking
46          200.0          400.0          Paid    NetBanking
47          350.0          150.0       Pending    NetBanking
48          350.0          600.0          Paid    NetBanking
49          750.0          250.0      Refunded           UPI
50          200.0          150.0          Paid           UPI
51            NaN          400.0       Pending          Card
52         1000.0          600.0          Paid          Card
53          350.0          150.0       Pending    NetBanking
54          200.0          150.0          Paid    NetBanking
55          350.0            NaN          Paid    NetBanking
56          500.0          150.0          Paid          Card
57          350.0          250.0          Paid          Card
58          350.0          150.0          Paid          Card
59         1000.0            NaN          Paid          Card

In [ ]:
df['City']=df['City'].fillna("Unknown")
df['PaymentMethod']=df['PaymentMethod'].fillna("Unknown")
df['Age']=df['Age'].fillna(df["Age"].median())
df['MarketingCost']=df['MarketingCost'].fillna(df["MarketingCost"].median())
df['COGS_per_unit']=df['COGS_per_unit'].fillna(df["COGS_per_unit"].median())
df['DiscountPct']=df['DiscountPct'].fillna(df["DiscountPct"].median())

In [ ]:
print(df)

    OrderID   OrderDate  CustomerID       City   Age        Channel  \
0      1001  01-01-2025        5039    Unknown  21.0  Instagram Ads
1      1002  02-01-2025        5029       Pune  31.0  Instagram Ads
2      1003  03-01-2025        5015        Goa  31.0  Instagram Ads
3      1004  04-01-2025        5043       Pune  29.0     Google Ads
4      1005  05-01-2025        5008       Pune  31.0  Instagram Ads
5      1006  06-01-2025        5021        Goa  23.0       Referral
6      1007  07-01-2025        5039  Bangalore  19.0        Organic
7      1008  08-01-2025        5019       Pune  31.0  Instagram Ads
8      1009  09-01-2025        5023       Pune  31.0     Google Ads
9      1010  10-01-2025        5011        Goa  21.0     Google Ads
10     1011  11-01-2025        5011       Pune  21.0  Instagram Ads
11     1012  12-01-2025        5024       Pune  25.0        Organic
12     1013  13-01-2025        5036        Goa  27.0  Instagram Ads
13     1014  14-01-2025        5040        Goa  23.0     Google Ads
14     1015  15-01-2025        5024    Belgaum  31.0   Facebook Ads
15     1016  16-01-2025        5003  Bangalore  27.0       Referral
16     1017  17-01-2025        5022  Bangalore  31.0     Google Ads
17     1018  18-01-2025        5002       Pune  19.0  Instagram Ads
18     1019  19-01-2025        5024  Bangalore  25.0       Referral
19     1020  20-01-2025        5044       Pune  27.0  Instagram Ads
20     1021  21-01-2025        5030    Belgaum  33.0  Instagram Ads
21     1022  22-01-2025        5038        Goa  25.0   Facebook Ads
22     1023  23-01-2025        5002        Goa  29.0       Referral
23     1024  24-01-2025        5021        Goa  27.0       Referral
24     1025  25-01-2025        5033    Unknown  31.0   Facebook Ads
25     1026  26-01-2025        5012    Belgaum  31.0     Google Ads
26     1027  27-01-2025        5022  Bangalore  27.0  Instagram Ads
27     1028  28-01-2025        5044  Bangalore  31.0        Organic
28     1029  29-01-2025        5025    Belgaum  23.0  Instagram Ads
29     1030  30-01-2025        5049    Belgaum  27.0  Instagram Ads
30     1031  31-01-2025        5027    Belgaum  25.0     Google Ads
31     1032  01-02-2025        5042    Belgaum  27.0  Instagram Ads
32     1033  02-02-2025        5028        Goa  33.0   Facebook Ads
33     1034  03-02-2025        5016      Hubli  31.0   Facebook Ads
34     1035  04-02-2025        5015    Unknown  23.0       Referral
35     1036  05-02-2025        5047    Belgaum  23.0        Organic
36     1037  06-02-2025        5044      Hubli  27.0  Instagram Ads
37     1038  07-02-2025        5003      Hubli  27.0  Instagram Ads
38     1039  08-02-2025        5037    Belgaum  21.0     Google Ads
39     1040  09-02-2025        5007    Unknown  21.0   Facebook Ads
40     1041  10-02-2025        5021  Bangalore  27.0        Organic
41     1042  11-02-2025        5009       Pune  27.0       Referral
42     1043  12-02-2025        5039       Pune  19.0   Facebook Ads
43     1044  13-02-2025        5018    Belgaum  27.0       Referral
44     1045  14-02-2025        5004        Goa  29.0     Google Ads
45     1046  15-02-2025        5025    Belgaum  25.0     Google Ads
46     1047  16-02-2025        5014        Goa  25.0  Instagram Ads
47     1048  17-02-2025        5009       Pune  25.0        Organic
48     1049  18-02-2025        5026    Belgaum  25.0       Referral
49     1050  19-02-2025        5002  Bangalore  25.0   Facebook Ads
50     1051  20-02-2025        5020      Hubli  29.0     Google Ads
51     1052  21-02-2025        5028        Goa  29.0  Instagram Ads
52     1053  22-02-2025        5047    Unknown  23.0  Instagram Ads
53     1054  23-02-2025        5007      Hubli  33.0       Referral
54     1055  24-02-2025        5044    Belgaum  27.0     Google Ads
55     1056  25-02-2025        5008      Hubli  31.0        Organic
56     1057  26-02-2025        5047  Bangalore  25.0     Google Ads
57     1058  27-02-2025        5035      Hubli  19.0       Referral
58     1059  28-02-2025        5014    Belgaum  31.0       Referral
59     1060  01-03-2025        5017  Bangalore  29.0     Google Ads

            Campaign           ProductCategory  Units  UnitPrice  DiscountPct  \
0   Retargeting_Push  Digital Marketing Course      2       1999         0.20
1    Brand_Awareness  Digital Marketing Course      1       1999         0.00
2     New_Year_Blast             Workshop Pass      5        499         0.00
3    Brand_Awareness                SAP Course      4       1999         0.20
4    Brand_Awareness                SAP Course      2       1999         0.15
5   Retargeting_Push                    E-book      1       1999         0.10
6   Retargeting_Push                SAP Course      4        999         0.10
7        Diwali_Sale                SAP Course      5       1499         0.00
8        Diwali_Sale                SAP Course      4        799         0.15
9     New_Year_Blast     Data Analytics Course      1        999         0.10
10       Diwali_Sale                    E-book      4       1999         0.15
11   Brand_Awareness  Digital Marketing Course      3        499         0.15
12  Retargeting_Push             Workshop Pass      4       1999         0.00
13       Diwali_Sale  Digital Marketing Course      2       1499         0.10
14       Diwali_Sale                    E-book      2       1999         0.20
15    New_Year_Blast             Workshop Pass      3        499         0.00
16    New_Year_Blast                    E-book      1       1499         0.10
17   Brand_Awareness                SAP Course      2       1999         0.10
18  Retargeting_Push             Workshop Pass      5       1499         0.10
19    New_Year_Blast                SAP Course      2        799         0.10
20       Diwali_Sale  Digital Marketing Course      2        799         0.10
21  Retargeting_Push  Digital Marketing Course      1       1999         0.15
22  Retargeting_Push             Workshop Pass      4       1499         0.00
23       Diwali_Sale             Workshop Pass      2        499         0.15
24    New_Year_Blast                    E-book      3       1999         0.20
25       Diwali_Sale                    E-book      4        799         0.10
26  Retargeting_Push                SAP Course      5        799         0.00
27    Referral_Bonus             Workshop Pass      1       1999         0.10
28    Referral_Bonus  Digital Marketing Course      5       1499         0.00
29   Brand_Awareness                    E-book      4        799         0.15
30       Diwali_Sale                    E-book      4       1499         0.00
31       Diwali_Sale  Digital Marketing Course      4        799         0.10
32   Brand_Awareness                    E-book      5        799         0.20
33   Brand_Awareness                SAP Course      4        999         0.00
34   Brand_Awareness             Workshop Pass      5        799         0.00
35  Retargeting_Push  Digital Marketing Course      4        499         0.00
36       Diwali_Sale             Workshop Pass      3       1999         0.00
37  Retargeting_Push                    E-book      4       1999         0.20
38   Brand_Awareness                    E-book      5       1499         0.10
39       Diwali_Sale  Digital Marketing Course      2        799         0.00
40  Retargeting_Push                SAP Course      4        499         0.00
41  Retargeting_Push     Data Analytics Course      2       1499         0.20
42   Brand_Awareness  Digital Marketing Course      3        999         0.20
43       Diwali_Sale     Data Analytics Course      1       1499         0.15
44   Brand_Awareness     Data Analytics Course      3       1499         0.00
45       Diwali_Sale                SAP Course      4        799         0.15
46    Referral_Bonus     Data Analytics Course      2        999         0.20
47    New_Year_Blast     Data Analytics Course      2       1499         0.20
48    New_Year_Blast                SAP Course      5        499         0.10
49    New_Year_Blast     Data Analytics Course      2        499         0.00
50   Brand_Awareness     Data Analytics Course      5       1999         0.15
51    Referral_Bonus     Data Analytics Course      1        999         0.10
52       Diwali_Sale  Digital Marketing Course      4        999         0.20
53  Retargeting_Push  Digital Marketing Course      5       1999         0.15
54       Diwali_Sale  Digital Marketing Course      1       1499         0.10
55  Retargeting_Push                SAP Course      2        999         0.20
56       Diwali_Sale                    E-book      2        499         0.00
57    Referral_Bonus     Data Analytics Course      1        499         0.20
58  Retargeting_Push     Data Analytics Course      2        799         0.00
59   Brand_Awareness                SAP Course      1        999         0.15

    MarketingCost  COGS_per_unit PaymentStatus PaymentMethod
0          1000.0          150.0       Pending           UPI
1           200.0          150.0      Refunded           UPI
2           500.0          250.0          Paid       Unknown
3           200.0          400.0          Paid           UPI
4           200.0          600.0          Paid          Card
5           200.0          600.0      Refunded    NetBanking
6           500.0          150.0      Refunded       Unknown
7           200.0          150.0          Paid    NetBanking
8          1000.0          250.0          Paid           UPI
9           500.0          600.0          Paid           UPI
10          500.0          150.0          Paid           UPI
11          200.0          400.0          Paid          Card
12          750.0          400.0          Paid          Card
13          750.0          150.0      Refunded    NetBanking
14         1000.0          150.0          Paid           UPI
15          200.0          600.0          Paid       Unknown
16          500.0          600.0       Pending          Card
17          500.0          250.0      Refunded       Unknown
18          200.0          600.0      Refunded          Card
19          750.0          400.0          Paid           UPI
20          500.0          400.0          Paid    NetBanking
21          500.0          150.0          Paid           UPI
22          350.0          600.0          Paid           UPI
23         1000.0          250.0          Paid          Card
24         1000.0          400.0          Paid           UPI
25          500.0          400.0          Paid           UPI
26          750.0          250.0          Paid          Card
27          200.0          250.0          Paid    NetBanking
28          750.0          400.0          Paid    NetBanking
29          500.0          400.0          Paid          Card
30         1000.0          250.0          Paid          Card
31          500.0          400.0          Paid          Card
32         1000.0          150.0          Paid          Card
33          200.0          150.0          Paid          Card
34         1000.0          250.0          Paid    NetBanking
35         1000.0          600.0          Paid    NetBanking
36          350.0          250.0          Paid          Card
37          350.0          250.0          Paid           UPI
38          350.0          600.0      Refunded          Card
39         1000.0          600.0          Paid           UPI
40          500.0          600.0          Paid          Card
41         1000.0          150.0      Refunded          Card
42          500.0          400.0          Paid    NetBanking
43          500.0          150.0       Pending       Unknown
44          350.0          250.0          Paid           UPI
45          750.0          150.0          Paid    NetBanking
46          200.0          400.0          Paid    NetBanking
47          350.0          150.0       Pending    NetBanking
48          350.0          600.0          Paid    NetBanking
49          750.0          250.0      Refunded           UPI
50          200.0          150.0          Paid           UPI
51          500.0          400.0       Pending          Card
52         1000.0          600.0          Paid          Card
53          350.0          150.0       Pending    NetBanking
54          200.0          150.0          Paid    NetBanking
55          350.0          250.0          Paid    NetBanking
56          500.0          150.0          Paid          Card
57          350.0          250.0          Paid          Card
58          350.0          150.0          Paid          Card
59         1000.0          250.0          Paid          Card

In [ ]:
df.isnull().sum()

OrderID            0
OrderDate          0
CustomerID         0
City               0
Age                0
Channel            0
Campaign           0
ProductCategory    0
Units              0
UnitPrice          0
DiscountPct        0
MarketingCost      0
COGS_per_unit      0
PaymentStatus      0
PaymentMethod      0
dtype: int64

In [ ]:
df.to_csv('Marketing_Finance_Project_clean.csv')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')